migration_plan_path: "migrations.csv"
results: "results.csv"
clean_file: "clean.sh"
atm_root: "/Users/usiusi/Documents/Repositories/AppTestMigrator/ATM-Modified"
migration_log_dir: "log"
generated_dir: "generated"
migration_timeout: 3600
embedding:
  - wm
#  - w2v
#  - nnlm
#  - use
#  - bert
#  - glove
#  - fast
#  - jaccard
#  - edit_distance
train_set:
  - android
  - blogs
  - standard
  - empty
  - googleplay
algorithm:
  - craftdroid
  - custom
  - atm_0
descriptors:
  - union
  - intersection
  - craftdroid
  - atm
clusters:
  app_to_cluster: "/Users/usiusi/Documents/Repositories/word-embedding/embedding/app_to_cluster.csv"
  app_info: "/Users/usiusi/Documents/Repositories/word-embedding/embedding/app_info.csv"
  topic_model: "/Users/usiusi/Documents/Repositories/AppClustering/model_selector_data/"
