migration_plan_path: "migrations.csv"
results: "results.csv"
clean_file: "clean.sh"
atm_root: "/root/test-reuse/atm/ATM-Modified"
migration_log_dir: "log"
generated_dir: "generated"
config_samples: 'config_sample.csv'
emulator: "emulator1"
migration_timeout: 3600
install_timeout: 240
embedding:
  - wm
  - w2v
  - nnlm
  - use
  - bert
  - glove
  - fast
  - jaccard
  - edit_distance
train_set:
  - android
  - blogs
  - standard
  - empty
  - googleplay
algorithm:
  - craftdroid
  - custom
  - atm
  - perfect
  - adaptdroid
descriptors:
  - union
  - intersection
  - craftdroid
  - atm
clusters:
  app_to_cluster: "/Users/usiusi/Documents/Repositories/word-embedding/embedding/app_to_cluster.csv"
  app_info: "/Users/usiusi/Documents/Repositories/word-embedding/embedding/app_info.csv"
  topic_model: "/Users/usiusi/Documents/Repositories/AppClustering/model_selector_data/"
